### ISSUE TITLE
Cannot install vue-intro

### ISSUE THREAD

**Issue by barntrax** [nblackburn/vue-intro#1]
Linux 3.13.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "vue-intro"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:nblackburn/intro.js.git /root/.npm/_git-remotes/git-github-com-nblackburn-intro-js-git-show-hints-7f0a3a78
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-nblackburn-intro-js-git-show-hints-7f0a3a78'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by nblackburn** [comment]
I have not been able to replicate this issue so i am going to close this for now.
